### PR TITLE
SPM-1616: improve waiting for db upgrade

### PR DESCRIPTION
**Pull request by psegedy**
- add env vars to skip updating users and db config
- start migration only if the latest migration is not applied
- add init containers for other pods to wait for migration

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by psegedy** [comment]
hmm looks like there is something wrong in init containers, they keep running, need to debug it in ephemeral

**Comment by psegedy** [comment]
```
exec: \"./database_admin/check-upgraded.sh\": permission denied"
```
🤦

**Comment by psegedy** [comment]
@michalslomczynski it's should be fixed now

**Review by michalslomczynski — APPROVED** [review]

**Pull request merged**
