### PR TITLE
Move syncing advisories into separate goroutine

### PR DESCRIPTION
**Pull request by semtexzv**
Should resolve vmaas_sync crashing issue

### CODE REVIEW

**Review by Josca — CHANGES_REQUESTED** [review]
1) Why should this help?
2) Tests pipeline failed.

**Comment by semtexzv** [comment]
It seems that connection to vmaas times out in prod

**Comment by Josca** [comment]
So it does not solve the whole issue - advisories are not synced. It mill maybe just resolve issue of restarting, right?

**Comment by Josca** [comment]
@semtexzv ok, makes sense, so just ensure passing pipeline and then feel free to merge it.

**Comment by semtexzv** [comment]
Superseded by https://github.com/RedHatInsights/patchman-engine/pull/376

**Pull request closed without merging**
