### PR TITLE
Update security compliance

### PR DESCRIPTION
**Pull request by SteveHNH**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by casey-williams-rh — APPROVED** [review]
👍

**Comment by MichaelMraka** [comment]
Are you sure you want to merge master code which contains not yet verified code and enabled features?

**Comment by SteveHNH** [comment]
@MichaelMraka we've mainly been tracking with master for most repos because they use that as their release branch, but I _did_ just notice you have a stable branch. Would that be the better choice?

**Comment by MichaelMraka** [comment]
@SteveHNH Unfortunately no, `stable` branch is unused for about 2 years.
We don't have any prod tracking branch.
Deployments to the prod go from version tags (in`master`) after QEs verify them.

**Pull request closed without merging**
