### PR TITLE
SPM-889: Use vmaas /pkglist endpoint to sync packages

### PR DESCRIPTION
**Pull request by Josca**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by MichaelMraka — APPROVED** [review]
lgtm

Just a note: would not be /pkglist sync better default value for future?

**Comment by Josca** [comment]
Yes, but for now I wanted to keep current behaviour by default. Later we can deprecated /pkgtree sync.

**Comment by Josca** [comment]
CI pipeline is failing because of broken x-join. I've tested in ephemeral env and it works. Merging.

**Pull request merged**
